// lib/examples.js
// Built-in example system dynamics models for learning

export const EXAMPLE_DOMAINS = {
  classic: {
    id: 'classic',
    name: 'Classic Models',
    description: 'Foundational system dynamics models from the literature',
    color: '#6366f1',
  },
  personal: {
    id: 'personal',
    name: 'Personal Development',
    description: 'Health, learning, habits, and personal growth',
    color: '#ec4899',
  },
  global: {
    id: 'global',
    name: 'Global Challenges',
    description: 'World peace, climate, inequality, and humanity\'s big questions',
    color: '#3b82f6',
  },
  society: {
    id: 'society',
    name: 'Society & Community',
    description: 'Education, healthcare, cities, and social movements',
    color: '#8b5cf6',
  },
  technology: {
    id: 'technology',
    name: 'Technology & AI',
    description: 'Digital transformation, AI, social media dynamics',
    color: '#06b6d4',
  },
  business: {
    id: 'business',
    name: 'Business & Management',
    description: 'Business strategy, operations, and management models',
    color: '#10b981',
  },
  project: {
    id: 'project',
    name: 'Project Management',
    description: 'Project dynamics and delivery challenges',
    color: '#f59e0b',
  },
  environment: {
    id: 'environment',
    name: 'Environment & Sustainability',
    description: 'Ecological and sustainability models',
    color: '#22c55e',
  },
};

export const EXAMPLES = {
  // === CLASSIC MODELS ===
  'population-growth': {
    id: 'population-growth',
    name: 'Population Growth',
    domain: 'classic',
    difficulty: 'beginner',
    type: 'stockflow',
    description: 'The foundational stock-flow model showing exponential growth dynamics.',
    situation: 'A population grows based on birth rate. The larger the population, the more births occur, creating a reinforcing feedback loop.',
    keyLessons: [
      'Stocks accumulate over time',
      'Flows are rates of change',
      'Reinforcing loops create exponential growth',
    ],
    elements: [
      { id: 'population', type: 'stock', label: 'Population', x: 300, y: 200, value: 100 },
      { id: 'births', type: 'flow', label: 'Births', x: 150, y: 200 },
      { id: 'birth-rate', type: 'converter', label: 'Birth Rate', x: 150, y: 100, value: 0.03 },
      { id: 'source', type: 'cloud', label: '', x: 50, y: 200 },
    ],
    connections: [
      { id: 'c1', source: 'source', target: 'births', type: 'flow_pipe' },
      { id: 'c2', source: 'births', target: 'population', type: 'flow_pipe' },
      { id: 'c3', source: 'birth-rate', target: 'births', type: 'connector' },
      { id: 'c4', source: 'population', target: 'births', type: 'connector' },
    ],
    loops: [
      { id: 'R1', name: 'Population Growth', type: 'reinforcing', nodes: ['population', 'births'], description: 'More people leads to more births, which increases population' },
    ],
  },

  'bathtub': {
    id: 'bathtub',
    name: 'Bathtub Dynamics',
    domain: 'classic',
    difficulty: 'beginner',
    type: 'stockflow',
    description: 'The classic bathtub model demonstrating inflow and outflow balancing.',
    situation: 'A bathtub fills with water from a faucet and drains through the drain. The water level represents a stock that changes based on these two flows.',
    keyLessons: [
      'Stocks can have multiple inflows and outflows',
      'Equilibrium occurs when inflows equal outflows',
      'The stock level persists even when flows stop',
    ],
    elements: [
      { id: 'water-level', type: 'stock', label: 'Water Level', x: 300, y: 200, value: 50 },
      { id: 'inflow', type: 'flow', label: 'Faucet', x: 150, y: 200 },
      { id: 'outflow', type: 'flow', label: 'Drain', x: 450, y: 200 },
      { id: 'source', type: 'cloud', label: '', x: 50, y: 200 },
      { id: 'sink', type: 'cloud', label: '', x: 550, y: 200 },
      { id: 'faucet-rate', type: 'parameter', label: 'Faucet Rate', x: 150, y: 100, value: 10 },
      { id: 'drain-rate', type: 'parameter', label: 'Drain Rate', x: 450, y: 100, value: 0.1 },
    ],
    connections: [
      { id: 'c1', source: 'source', target: 'inflow', type: 'flow_pipe' },
      { id: 'c2', source: 'inflow', target: 'water-level', type: 'flow_pipe' },
      { id: 'c3', source: 'water-level', target: 'outflow', type: 'flow_pipe' },
      { id: 'c4', source: 'outflow', target: 'sink', type: 'flow_pipe' },
      { id: 'c5', source: 'faucet-rate', target: 'inflow', type: 'connector' },
      { id: 'c6', source: 'drain-rate', target: 'outflow', type: 'connector' },
      { id: 'c7', source: 'water-level', target: 'outflow', type: 'connector' },
    ],
    loops: [
      { id: 'B1', name: 'Draining', type: 'balancing', nodes: ['water-level', 'outflow'], description: 'Higher water level increases drain rate, reducing water level' },
    ],
  },

  'limits-to-growth': {
    id: 'limits-to-growth',
    name: 'Limits to Growth',
    domain: 'classic',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'The S-curve growth pattern when reinforcing growth meets limiting factors.',
    situation: 'Initial exponential growth eventually slows as the system approaches carrying capacity limits.',
    keyLessons: [
      'Reinforcing loops dominate early growth',
      'Balancing loops dominate as limits approach',
      'S-curve behavior is common in real systems',
      'Delays can cause overshoot',
    ],
    elements: [
      { id: 'population', type: 'variable', label: 'Population', x: 300, y: 200 },
      { id: 'growth-rate', type: 'variable', label: 'Growth Rate', x: 150, y: 200 },
      { id: 'resources', type: 'variable', label: 'Available Resources', x: 450, y: 200 },
      { id: 'carrying-capacity', type: 'variable', label: 'Carrying Capacity', x: 450, y: 100 },
      { id: 'resource-consumption', type: 'variable', label: 'Resource Consumption', x: 300, y: 350 },
    ],
    connections: [
      { id: 'c1', source: 'growth-rate', target: 'population', type: 'positive' },
      { id: 'c2', source: 'population', target: 'growth-rate', type: 'positive' },
      { id: 'c3', source: 'population', target: 'resource-consumption', type: 'positive' },
      { id: 'c4', source: 'resource-consumption', target: 'resources', type: 'negative' },
      { id: 'c5', source: 'resources', target: 'growth-rate', type: 'positive' },
      { id: 'c6', source: 'carrying-capacity', target: 'resources', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Growth Engine', type: 'reinforcing', nodes: ['population', 'growth-rate'], description: 'Population drives growth rate which increases population' },
      { id: 'B1', name: 'Resource Limits', type: 'balancing', nodes: ['population', 'resource-consumption', 'resources', 'growth-rate'], description: 'Population depletes resources, limiting future growth' },
    ],
  },

  // === BUSINESS MODELS ===
  'market-growth': {
    id: 'market-growth',
    name: 'Market Growth & Saturation',
    domain: 'business',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'Product adoption dynamics showing how word-of-mouth drives growth until market saturation.',
    situation: 'A new product enters the market. Early adopters spread word-of-mouth, attracting new customers. As the potential market shrinks, growth slows.',
    keyLessons: [
      'Word-of-mouth creates reinforcing growth',
      'Market saturation creates natural limits',
      'The gap between potential and actual customers matters',
    ],
    elements: [
      { id: 'customers', type: 'variable', label: 'Customers', x: 300, y: 200 },
      { id: 'word-of-mouth', type: 'variable', label: 'Word of Mouth', x: 150, y: 300 },
      { id: 'adoption-rate', type: 'variable', label: 'Adoption Rate', x: 300, y: 350 },
      { id: 'potential-customers', type: 'variable', label: 'Potential Customers', x: 450, y: 200 },
      { id: 'market-size', type: 'variable', label: 'Total Market Size', x: 450, y: 80 },
    ],
    connections: [
      { id: 'c1', source: 'customers', target: 'word-of-mouth', type: 'positive' },
      { id: 'c2', source: 'word-of-mouth', target: 'adoption-rate', type: 'positive' },
      { id: 'c3', source: 'adoption-rate', target: 'customers', type: 'positive' },
      { id: 'c4', source: 'adoption-rate', target: 'potential-customers', type: 'negative' },
      { id: 'c5', source: 'potential-customers', target: 'adoption-rate', type: 'positive' },
      { id: 'c6', source: 'market-size', target: 'potential-customers', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Word of Mouth', type: 'reinforcing', nodes: ['customers', 'word-of-mouth', 'adoption-rate'], description: 'Customers spread the word, attracting more customers' },
      { id: 'B1', name: 'Market Saturation', type: 'balancing', nodes: ['adoption-rate', 'potential-customers'], description: 'Fewer potential customers means slower adoption' },
    ],
  },

  'service-quality': {
    id: 'service-quality',
    name: 'Service Quality Trap',
    domain: 'business',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How success can undermine the very factors that created it.',
    situation: 'A successful service attracts more customers, but without proportional capacity increase, service quality degrades, eventually driving customers away.',
    keyLessons: [
      'Success can carry the seeds of its own decline',
      'Capacity investments may lag behind demand',
      'Quality is often sacrificed for quantity under pressure',
    ],
    elements: [
      { id: 'customers', type: 'variable', label: 'Customers', x: 300, y: 150 },
      { id: 'service-quality', type: 'variable', label: 'Service Quality', x: 150, y: 250 },
      { id: 'capacity', type: 'variable', label: 'Service Capacity', x: 300, y: 350 },
      { id: 'revenue', type: 'variable', label: 'Revenue', x: 450, y: 150 },
      { id: 'capacity-investment', type: 'variable', label: 'Capacity Investment', x: 450, y: 350 },
      { id: 'workload', type: 'variable', label: 'Workload per Staff', x: 150, y: 350 },
    ],
    connections: [
      { id: 'c1', source: 'service-quality', target: 'customers', type: 'positive' },
      { id: 'c2', source: 'customers', target: 'revenue', type: 'positive' },
      { id: 'c3', source: 'customers', target: 'workload', type: 'positive' },
      { id: 'c4', source: 'workload', target: 'service-quality', type: 'negative' },
      { id: 'c5', source: 'revenue', target: 'capacity-investment', type: 'positive' },
      { id: 'c6', source: 'capacity-investment', target: 'capacity', type: 'positive' },
      { id: 'c7', source: 'capacity', target: 'workload', type: 'negative' },
    ],
    loops: [
      { id: 'R1', name: 'Growth Loop', type: 'reinforcing', nodes: ['service-quality', 'customers', 'revenue', 'capacity-investment', 'capacity', 'workload'], description: 'Quality attracts customers, funds capacity, improves quality' },
      { id: 'B1', name: 'Quality Erosion', type: 'balancing', nodes: ['service-quality', 'customers', 'workload'], description: 'More customers overload capacity, degrading quality' },
    ],
  },

  // === PROJECT MANAGEMENT ===
  'brooks-law': {
    id: 'brooks-law',
    name: "Brooks's Law",
    domain: 'project',
    difficulty: 'advanced',
    type: 'cld',
    description: '"Adding people to a late project makes it later" - the classic software project trap.',
    situation: 'A software project falls behind schedule. Management adds more developers, but training overhead and communication complexity initially slow progress further.',
    keyLessons: [
      'New team members need ramp-up time',
      'Communication overhead grows with team size',
      'Short-term fixes can worsen long-term problems',
      'There are no silver bullets in project management',
    ],
    elements: [
      { id: 'schedule-pressure', type: 'variable', label: 'Schedule Pressure', x: 150, y: 150 },
      { id: 'team-size', type: 'variable', label: 'Team Size', x: 300, y: 100 },
      { id: 'productivity', type: 'variable', label: 'Productivity', x: 450, y: 150 },
      { id: 'progress', type: 'variable', label: 'Progress', x: 450, y: 280 },
      { id: 'training-overhead', type: 'variable', label: 'Training Overhead', x: 300, y: 230 },
      { id: 'communication-overhead', type: 'variable', label: 'Communication Overhead', x: 300, y: 350 },
      { id: 'experienced-devs', type: 'variable', label: 'Experienced Developers', x: 150, y: 280 },
    ],
    connections: [
      { id: 'c1', source: 'schedule-pressure', target: 'team-size', type: 'positive' },
      { id: 'c2', source: 'team-size', target: 'training-overhead', type: 'positive' },
      { id: 'c3', source: 'team-size', target: 'communication-overhead', type: 'positive' },
      { id: 'c4', source: 'training-overhead', target: 'productivity', type: 'negative' },
      { id: 'c5', source: 'training-overhead', target: 'experienced-devs', type: 'negative' },
      { id: 'c6', source: 'communication-overhead', target: 'productivity', type: 'negative' },
      { id: 'c7', source: 'productivity', target: 'progress', type: 'positive' },
      { id: 'c8', source: 'progress', target: 'schedule-pressure', type: 'negative' },
      { id: 'c9', source: 'experienced-devs', target: 'training-overhead', type: 'negative' },
    ],
    loops: [
      { id: 'B1', name: 'Intended Fix', type: 'balancing', nodes: ['schedule-pressure', 'team-size', 'productivity', 'progress'], description: 'Pressure leads to hiring, should increase progress' },
      { id: 'R1', name: 'Training Burden', type: 'reinforcing', nodes: ['team-size', 'training-overhead', 'experienced-devs'], description: 'New hires burden experienced devs, slowing training' },
      { id: 'B2', name: 'Communication Tax', type: 'balancing', nodes: ['team-size', 'communication-overhead', 'productivity', 'progress', 'schedule-pressure'], description: 'Larger teams have more overhead' },
    ],
  },

  'technical-debt': {
    id: 'technical-debt',
    name: 'Technical Debt Trap',
    domain: 'project',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How taking shortcuts accumulates hidden costs that slow future development.',
    situation: 'Under schedule pressure, teams take technical shortcuts. These accumulate as "debt" that makes future changes harder, creating more pressure.',
    keyLessons: [
      'Short-term gains often have long-term costs',
      'Technical debt compounds over time',
      'Paying down debt requires deliberate investment',
    ],
    elements: [
      { id: 'schedule-pressure', type: 'variable', label: 'Schedule Pressure', x: 150, y: 150 },
      { id: 'shortcuts', type: 'variable', label: 'Shortcuts Taken', x: 300, y: 100 },
      { id: 'tech-debt', type: 'variable', label: 'Technical Debt', x: 450, y: 150 },
      { id: 'dev-velocity', type: 'variable', label: 'Development Velocity', x: 450, y: 300 },
      { id: 'feature-delivery', type: 'variable', label: 'Feature Delivery', x: 300, y: 350 },
      { id: 'code-quality', type: 'variable', label: 'Code Quality', x: 300, y: 200 },
    ],
    connections: [
      { id: 'c1', source: 'schedule-pressure', target: 'shortcuts', type: 'positive' },
      { id: 'c2', source: 'shortcuts', target: 'tech-debt', type: 'positive' },
      { id: 'c3', source: 'shortcuts', target: 'code-quality', type: 'negative' },
      { id: 'c4', source: 'tech-debt', target: 'dev-velocity', type: 'negative' },
      { id: 'c5', source: 'code-quality', target: 'dev-velocity', type: 'positive' },
      { id: 'c6', source: 'dev-velocity', target: 'feature-delivery', type: 'positive' },
      { id: 'c7', source: 'feature-delivery', target: 'schedule-pressure', type: 'negative' },
    ],
    loops: [
      { id: 'B1', name: 'Quick Fix', type: 'balancing', nodes: ['schedule-pressure', 'shortcuts', 'feature-delivery'], description: 'Shortcuts speed delivery, reducing pressure (short-term)' },
      { id: 'R1', name: 'Debt Spiral', type: 'reinforcing', nodes: ['shortcuts', 'tech-debt', 'dev-velocity', 'feature-delivery', 'schedule-pressure'], description: 'Shortcuts create debt, slowing velocity, increasing pressure for more shortcuts' },
    ],
  },

  // === PERSONAL DEVELOPMENT ===
  'healthy-eating': {
    id: 'healthy-eating',
    name: 'Healthy Eating Habits',
    domain: 'personal',
    difficulty: 'beginner',
    type: 'cld',
    description: 'Understanding why healthy eating is so hard to maintain and how habits compound over time.',
    situation: 'You want to eat healthier, but stress leads to comfort food cravings. Meanwhile, healthy eating improves energy and mood, making it easier to resist cravings.',
    keyLessons: [
      'Habits create self-reinforcing cycles',
      'Short-term comfort often conflicts with long-term health',
      'Energy levels affect willpower and decision-making',
      'Breaking cycles requires intervention at the right point',
    ],
    elements: [
      { id: 'healthy-eating', type: 'variable', label: 'Healthy Eating', x: 300, y: 150 },
      { id: 'energy-levels', type: 'variable', label: 'Energy Levels', x: 500, y: 150 },
      { id: 'willpower', type: 'variable', label: 'Willpower', x: 500, y: 280 },
      { id: 'stress', type: 'variable', label: 'Stress', x: 100, y: 280 },
      { id: 'comfort-food', type: 'variable', label: 'Comfort Food Cravings', x: 100, y: 150 },
      { id: 'weight', type: 'variable', label: 'Body Weight', x: 300, y: 380 },
      { id: 'self-image', type: 'variable', label: 'Self-Image', x: 500, y: 380 },
      { id: 'mood', type: 'variable', label: 'Mood', x: 300, y: 280 },
      { id: 'meal-prep-time', type: 'variable', label: 'Meal Prep Time', x: 100, y: 380 },
    ],
    connections: [
      { id: 'c1', source: 'healthy-eating', target: 'energy-levels', type: 'positive' },
      { id: 'c2', source: 'energy-levels', target: 'willpower', type: 'positive' },
      { id: 'c3', source: 'willpower', target: 'healthy-eating', type: 'positive' },
      { id: 'c4', source: 'stress', target: 'comfort-food', type: 'positive' },
      { id: 'c5', source: 'comfort-food', target: 'healthy-eating', type: 'negative' },
      { id: 'c6', source: 'healthy-eating', target: 'weight', type: 'negative' },
      { id: 'c7', source: 'weight', target: 'self-image', type: 'negative' },
      { id: 'c8', source: 'self-image', target: 'mood', type: 'positive' },
      { id: 'c9', source: 'mood', target: 'stress', type: 'negative' },
      { id: 'c10', source: 'energy-levels', target: 'mood', type: 'positive' },
      { id: 'c11', source: 'meal-prep-time', target: 'healthy-eating', type: 'positive' },
      { id: 'c12', source: 'stress', target: 'meal-prep-time', type: 'negative' },
    ],
    loops: [
      { id: 'R1', name: 'Vitality Loop', type: 'reinforcing', nodes: ['healthy-eating', 'energy-levels', 'willpower'], description: 'Good food gives energy, energy enables better choices' },
      { id: 'R2', name: 'Self-Image Boost', type: 'reinforcing', nodes: ['healthy-eating', 'weight', 'self-image', 'mood', 'stress', 'comfort-food'], description: 'Health improves self-image, reduces stress eating' },
      { id: 'B1', name: 'Stress Eating', type: 'balancing', nodes: ['stress', 'comfort-food', 'healthy-eating', 'mood'], description: 'Stress triggers comfort eating, disrupting healthy patterns' },
    ],
  },

  'learning-mastery': {
    id: 'learning-mastery',
    name: 'The Learning Flywheel',
    domain: 'personal',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How learning creates compound returns and why starting is the hardest part.',
    situation: 'Learning a new skill feels slow at first, but as knowledge builds, learning accelerates. Early struggles can cause abandonment, but persistence creates exponential growth.',
    keyLessons: [
      'Learning compounds - knowledge builds on knowledge',
      'The "valley of despair" causes most people to quit',
      'Confidence and competence reinforce each other',
      'Teaching others accelerates your own mastery',
    ],
    elements: [
      { id: 'practice', type: 'variable', label: 'Practice Time', x: 150, y: 150 },
      { id: 'skill-level', type: 'variable', label: 'Skill Level', x: 350, y: 150 },
      { id: 'learning-speed', type: 'variable', label: 'Learning Speed', x: 550, y: 150 },
      { id: 'confidence', type: 'variable', label: 'Confidence', x: 350, y: 280 },
      { id: 'enjoyment', type: 'variable', label: 'Enjoyment', x: 550, y: 280 },
      { id: 'frustration', type: 'variable', label: 'Frustration', x: 150, y: 280 },
      { id: 'teaching-others', type: 'variable', label: 'Teaching Others', x: 550, y: 400 },
      { id: 'understanding', type: 'variable', label: 'Deep Understanding', x: 350, y: 400 },
      { id: 'opportunities', type: 'variable', label: 'New Opportunities', x: 150, y: 400 },
      { id: 'motivation', type: 'variable', label: 'Motivation', x: 150, y: 500 },
    ],
    connections: [
      { id: 'c1', source: 'practice', target: 'skill-level', type: 'positive' },
      { id: 'c2', source: 'skill-level', target: 'learning-speed', type: 'positive' },
      { id: 'c3', source: 'learning-speed', target: 'skill-level', type: 'positive' },
      { id: 'c4', source: 'skill-level', target: 'confidence', type: 'positive' },
      { id: 'c5', source: 'confidence', target: 'practice', type: 'positive' },
      { id: 'c6', source: 'skill-level', target: 'enjoyment', type: 'positive' },
      { id: 'c7', source: 'enjoyment', target: 'practice', type: 'positive' },
      { id: 'c8', source: 'frustration', target: 'practice', type: 'negative' },
      { id: 'c9', source: 'skill-level', target: 'frustration', type: 'negative' },
      { id: 'c10', source: 'skill-level', target: 'teaching-others', type: 'positive' },
      { id: 'c11', source: 'teaching-others', target: 'understanding', type: 'positive' },
      { id: 'c12', source: 'understanding', target: 'skill-level', type: 'positive' },
      { id: 'c13', source: 'skill-level', target: 'opportunities', type: 'positive' },
      { id: 'c14', source: 'opportunities', target: 'motivation', type: 'positive' },
      { id: 'c15', source: 'motivation', target: 'practice', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Mastery Flywheel', type: 'reinforcing', nodes: ['practice', 'skill-level', 'learning-speed'], description: 'More skill makes learning faster, accelerating progress' },
      { id: 'R2', name: 'Confidence Loop', type: 'reinforcing', nodes: ['practice', 'skill-level', 'confidence'], description: 'Skills build confidence, confidence drives practice' },
      { id: 'R3', name: 'Teaching Effect', type: 'reinforcing', nodes: ['skill-level', 'teaching-others', 'understanding'], description: 'Teaching deepens your own understanding' },
      { id: 'B1', name: 'Frustration Barrier', type: 'balancing', nodes: ['practice', 'skill-level', 'frustration'], description: 'Low skills cause frustration, reducing practice' },
    ],
  },

  'exercise-habit': {
    id: 'exercise-habit',
    name: 'Exercise Habit Formation',
    domain: 'personal',
    difficulty: 'beginner',
    type: 'cld',
    description: 'Why starting exercise is hard but maintaining it becomes easier over time.',
    situation: 'Exercise initially feels difficult and time-consuming. But regular exercise improves fitness, making it easier and more enjoyable, creating a virtuous cycle.',
    keyLessons: [
      'Initial barriers are highest - the first weeks are hardest',
      'Fitness makes exercise feel easier over time',
      'Identity shift ("I am a person who exercises") reinforces habits',
      'Missing days has compound effects on motivation',
    ],
    elements: [
      { id: 'exercise', type: 'variable', label: 'Exercise Frequency', x: 300, y: 150 },
      { id: 'fitness', type: 'variable', label: 'Fitness Level', x: 500, y: 150 },
      { id: 'perceived-difficulty', type: 'variable', label: 'Perceived Difficulty', x: 500, y: 280 },
      { id: 'endorphins', type: 'variable', label: 'Endorphins', x: 300, y: 280 },
      { id: 'motivation', type: 'variable', label: 'Motivation', x: 100, y: 280 },
      { id: 'energy', type: 'variable', label: 'Daily Energy', x: 100, y: 150 },
      { id: 'sleep-quality', type: 'variable', label: 'Sleep Quality', x: 100, y: 400 },
      { id: 'stress', type: 'variable', label: 'Stress', x: 300, y: 400 },
      { id: 'time-available', type: 'variable', label: 'Perceived Time Available', x: 500, y: 400 },
      { id: 'identity', type: 'variable', label: 'Athletic Identity', x: 300, y: 500 },
    ],
    connections: [
      { id: 'c1', source: 'exercise', target: 'fitness', type: 'positive' },
      { id: 'c2', source: 'fitness', target: 'perceived-difficulty', type: 'negative' },
      { id: 'c3', source: 'perceived-difficulty', target: 'exercise', type: 'negative' },
      { id: 'c4', source: 'exercise', target: 'endorphins', type: 'positive' },
      { id: 'c5', source: 'endorphins', target: 'motivation', type: 'positive' },
      { id: 'c6', source: 'motivation', target: 'exercise', type: 'positive' },
      { id: 'c7', source: 'exercise', target: 'energy', type: 'positive' },
      { id: 'c8', source: 'energy', target: 'exercise', type: 'positive' },
      { id: 'c9', source: 'exercise', target: 'sleep-quality', type: 'positive' },
      { id: 'c10', source: 'sleep-quality', target: 'energy', type: 'positive' },
      { id: 'c11', source: 'exercise', target: 'stress', type: 'negative' },
      { id: 'c12', source: 'stress', target: 'time-available', type: 'negative' },
      { id: 'c13', source: 'time-available', target: 'exercise', type: 'positive' },
      { id: 'c14', source: 'exercise', target: 'identity', type: 'positive' },
      { id: 'c15', source: 'identity', target: 'motivation', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Fitness Flywheel', type: 'reinforcing', nodes: ['exercise', 'fitness', 'perceived-difficulty'], description: 'Exercise builds fitness, making exercise feel easier' },
      { id: 'R2', name: 'Feel-Good Loop', type: 'reinforcing', nodes: ['exercise', 'endorphins', 'motivation'], description: 'Exercise releases endorphins, boosting motivation' },
      { id: 'R3', name: 'Energy Loop', type: 'reinforcing', nodes: ['exercise', 'energy'], description: 'Exercise paradoxically increases available energy' },
      { id: 'R4', name: 'Identity Lock-In', type: 'reinforcing', nodes: ['exercise', 'identity', 'motivation'], description: 'Regular exercise shifts identity, reinforcing commitment' },
    ],
  },

  'social-media-wellbeing': {
    id: 'social-media-wellbeing',
    name: 'Social Media & Mental Health',
    domain: 'personal',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How social media affects mental health through comparison, dopamine, and connection.',
    situation: 'Social media promises connection but often delivers comparison. The dopamine hits keep us scrolling while real-world connections and self-esteem suffer.',
    keyLessons: [
      'Comparison is the thief of joy',
      'Dopamine-driven habits are hard to break',
      'Online connection often displaces deeper offline connection',
      'Curated feeds create unrealistic expectations',
    ],
    elements: [
      { id: 'social-media-use', type: 'variable', label: 'Social Media Use', x: 300, y: 100 },
      { id: 'dopamine-hits', type: 'variable', label: 'Dopamine Hits', x: 500, y: 100 },
      { id: 'comparison', type: 'variable', label: 'Social Comparison', x: 100, y: 200 },
      { id: 'self-esteem', type: 'variable', label: 'Self-Esteem', x: 300, y: 200 },
      { id: 'anxiety', type: 'variable', label: 'Anxiety', x: 500, y: 200 },
      { id: 'real-connection', type: 'variable', label: 'Real-World Connection', x: 100, y: 320 },
      { id: 'loneliness', type: 'variable', label: 'Loneliness', x: 300, y: 320 },
      { id: 'fomo', type: 'variable', label: 'FOMO', x: 500, y: 320 },
      { id: 'productivity', type: 'variable', label: 'Productivity', x: 100, y: 440 },
      { id: 'time-available', type: 'variable', label: 'Free Time', x: 300, y: 440 },
      { id: 'sleep', type: 'variable', label: 'Sleep Quality', x: 500, y: 440 },
    ],
    connections: [
      { id: 'c1', source: 'social-media-use', target: 'dopamine-hits', type: 'positive' },
      { id: 'c2', source: 'dopamine-hits', target: 'social-media-use', type: 'positive' },
      { id: 'c3', source: 'social-media-use', target: 'comparison', type: 'positive' },
      { id: 'c4', source: 'comparison', target: 'self-esteem', type: 'negative' },
      { id: 'c5', source: 'self-esteem', target: 'anxiety', type: 'negative' },
      { id: 'c6', source: 'anxiety', target: 'social-media-use', type: 'positive' },
      { id: 'c7', source: 'social-media-use', target: 'real-connection', type: 'negative' },
      { id: 'c8', source: 'real-connection', target: 'loneliness', type: 'negative' },
      { id: 'c9', source: 'loneliness', target: 'social-media-use', type: 'positive' },
      { id: 'c10', source: 'social-media-use', target: 'fomo', type: 'positive' },
      { id: 'c11', source: 'fomo', target: 'social-media-use', type: 'positive' },
      { id: 'c12', source: 'social-media-use', target: 'productivity', type: 'negative' },
      { id: 'c13', source: 'social-media-use', target: 'time-available', type: 'negative' },
      { id: 'c14', source: 'time-available', target: 'real-connection', type: 'positive' },
      { id: 'c15', source: 'social-media-use', target: 'sleep', type: 'negative' },
      { id: 'c16', source: 'sleep', target: 'anxiety', type: 'negative' },
    ],
    loops: [
      { id: 'R1', name: 'Dopamine Trap', type: 'reinforcing', nodes: ['social-media-use', 'dopamine-hits'], description: 'Quick rewards drive more usage, seeking more rewards' },
      { id: 'R2', name: 'Anxiety Escape', type: 'reinforcing', nodes: ['social-media-use', 'comparison', 'self-esteem', 'anxiety'], description: 'Anxiety drives scrolling, which worsens anxiety' },
      { id: 'R3', name: 'Loneliness Loop', type: 'reinforcing', nodes: ['social-media-use', 'real-connection', 'loneliness'], description: 'Seeking connection online reduces real connection' },
      { id: 'R4', name: 'FOMO Cycle', type: 'reinforcing', nodes: ['social-media-use', 'fomo'], description: 'Fear of missing out drives constant checking' },
    ],
  },

  // === GLOBAL CHALLENGES ===
  'world-peace': {
    id: 'world-peace',
    name: 'Cycles of Conflict & Peace',
    domain: 'global',
    difficulty: 'advanced',
    type: 'cld',
    description: 'Understanding how conflicts escalate and what breaks the cycle toward lasting peace.',
    situation: 'Conflict between groups creates fear and grievances that perpetuate violence. Breaking this cycle requires addressing root causes while building trust and shared prosperity.',
    keyLessons: [
      'Fear and mistrust create self-fulfilling prophecies',
      'Economic interdependence raises the cost of conflict',
      'Cultural exchange humanizes "the other"',
      'Justice and acknowledgment help heal grievances',
      'Strong institutions provide alternatives to violence',
    ],
    elements: [
      { id: 'conflict', type: 'variable', label: 'Active Conflict', x: 300, y: 100 },
      { id: 'fear', type: 'variable', label: 'Fear of Other Group', x: 100, y: 180 },
      { id: 'grievances', type: 'variable', label: 'Historical Grievances', x: 500, y: 180 },
      { id: 'dehumanization', type: 'variable', label: 'Dehumanization', x: 100, y: 300 },
      { id: 'violence', type: 'variable', label: 'Violence', x: 300, y: 220 },
      { id: 'economic-cost', type: 'variable', label: 'Economic Cost', x: 500, y: 300 },
      { id: 'trade', type: 'variable', label: 'Trade & Exchange', x: 500, y: 420 },
      { id: 'cultural-exchange', type: 'variable', label: 'Cultural Exchange', x: 100, y: 420 },
      { id: 'trust', type: 'variable', label: 'Inter-group Trust', x: 300, y: 340 },
      { id: 'institutions', type: 'variable', label: 'Peace Institutions', x: 300, y: 460 },
      { id: 'shared-prosperity', type: 'variable', label: 'Shared Prosperity', x: 100, y: 540 },
      { id: 'justice', type: 'variable', label: 'Justice & Reconciliation', x: 500, y: 540 },
    ],
    connections: [
      { id: 'c1', source: 'conflict', target: 'fear', type: 'positive' },
      { id: 'c2', source: 'fear', target: 'dehumanization', type: 'positive' },
      { id: 'c3', source: 'dehumanization', target: 'violence', type: 'positive' },
      { id: 'c4', source: 'violence', target: 'conflict', type: 'positive' },
      { id: 'c5', source: 'violence', target: 'grievances', type: 'positive' },
      { id: 'c6', source: 'grievances', target: 'conflict', type: 'positive' },
      { id: 'c7', source: 'conflict', target: 'economic-cost', type: 'positive' },
      { id: 'c8', source: 'economic-cost', target: 'conflict', type: 'negative', curve: 40 },
      { id: 'c9', source: 'conflict', target: 'trade', type: 'negative' },
      { id: 'c10', source: 'trade', target: 'trust', type: 'positive' },
      { id: 'c11', source: 'trust', target: 'conflict', type: 'negative' },
      { id: 'c12', source: 'cultural-exchange', target: 'dehumanization', type: 'negative' },
      { id: 'c13', source: 'trust', target: 'cultural-exchange', type: 'positive' },
      { id: 'c14', source: 'institutions', target: 'conflict', type: 'negative' },
      { id: 'c15', source: 'trust', target: 'institutions', type: 'positive' },
      { id: 'c16', source: 'trade', target: 'shared-prosperity', type: 'positive' },
      { id: 'c17', source: 'shared-prosperity', target: 'grievances', type: 'negative' },
      { id: 'c18', source: 'justice', target: 'grievances', type: 'negative' },
      { id: 'c19', source: 'institutions', target: 'justice', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Violence Spiral', type: 'reinforcing', nodes: ['conflict', 'fear', 'dehumanization', 'violence'], description: 'Conflict breeds fear, which enables violence, escalating conflict' },
      { id: 'R2', name: 'Grievance Cycle', type: 'reinforcing', nodes: ['violence', 'grievances', 'conflict'], description: 'Violence creates grievances that fuel future conflict' },
      { id: 'R3', name: 'Peace Dividend', type: 'reinforcing', nodes: ['trust', 'trade', 'shared-prosperity'], description: 'Trust enables trade, prosperity builds more trust' },
      { id: 'B1', name: 'Economic Brake', type: 'balancing', nodes: ['conflict', 'economic-cost'], description: 'High costs of conflict eventually pressure settlement' },
      { id: 'B2', name: 'Humanization Path', type: 'balancing', nodes: ['trust', 'cultural-exchange', 'dehumanization', 'violence', 'conflict'], description: 'Exchange humanizes others, reducing violence' },
    ],
  },

  'climate-action': {
    id: 'climate-action',
    name: 'Climate Change Dynamics',
    domain: 'global',
    difficulty: 'advanced',
    type: 'cld',
    description: 'The complex dynamics of climate change, from emissions to impacts to political action.',
    situation: 'Greenhouse gas emissions drive warming, which creates visible impacts. But action is delayed by economic concerns, political challenges, and the slow pace of change.',
    keyLessons: [
      'Long delays between emissions and impacts obscure urgency',
      'Tipping points can trigger accelerating change',
      'Economic transition creates winners and losers',
      'Collective action problems require coordination',
      'Technology and policy must work together',
    ],
    elements: [
      { id: 'emissions', type: 'variable', label: 'GHG Emissions', x: 100, y: 100 },
      { id: 'atmospheric-co2', type: 'variable', label: 'Atmospheric CO2', x: 300, y: 100 },
      { id: 'temperature', type: 'variable', label: 'Global Temperature', x: 500, y: 100 },
      { id: 'extreme-weather', type: 'variable', label: 'Extreme Weather', x: 500, y: 220 },
      { id: 'economic-damage', type: 'variable', label: 'Economic Damage', x: 500, y: 340 },
      { id: 'public-concern', type: 'variable', label: 'Public Concern', x: 300, y: 340 },
      { id: 'political-will', type: 'variable', label: 'Political Will', x: 100, y: 340 },
      { id: 'climate-policy', type: 'variable', label: 'Climate Policy', x: 100, y: 220 },
      { id: 'clean-tech', type: 'variable', label: 'Clean Technology', x: 100, y: 460 },
      { id: 'fossil-economy', type: 'variable', label: 'Fossil Fuel Economy', x: 300, y: 220 },
      { id: 'resistance', type: 'variable', label: 'Political Resistance', x: 300, y: 460 },
      { id: 'ice-melt', type: 'variable', label: 'Ice Sheet Melt', x: 650, y: 160 },
      { id: 'sea-level', type: 'variable', label: 'Sea Level Rise', x: 650, y: 280 },
    ],
    connections: [
      { id: 'c1', source: 'emissions', target: 'atmospheric-co2', type: 'positive' },
      { id: 'c2', source: 'atmospheric-co2', target: 'temperature', type: 'positive' },
      { id: 'c3', source: 'temperature', target: 'extreme-weather', type: 'positive' },
      { id: 'c4', source: 'extreme-weather', target: 'economic-damage', type: 'positive' },
      { id: 'c5', source: 'economic-damage', target: 'public-concern', type: 'positive' },
      { id: 'c6', source: 'public-concern', target: 'political-will', type: 'positive' },
      { id: 'c7', source: 'political-will', target: 'climate-policy', type: 'positive' },
      { id: 'c8', source: 'climate-policy', target: 'emissions', type: 'negative' },
      { id: 'c9', source: 'climate-policy', target: 'fossil-economy', type: 'negative' },
      { id: 'c10', source: 'fossil-economy', target: 'emissions', type: 'positive' },
      { id: 'c11', source: 'fossil-economy', target: 'resistance', type: 'positive' },
      { id: 'c12', source: 'resistance', target: 'climate-policy', type: 'negative' },
      { id: 'c13', source: 'climate-policy', target: 'clean-tech', type: 'positive' },
      { id: 'c14', source: 'clean-tech', target: 'emissions', type: 'negative' },
      { id: 'c15', source: 'clean-tech', target: 'fossil-economy', type: 'negative' },
      { id: 'c16', source: 'temperature', target: 'ice-melt', type: 'positive' },
      { id: 'c17', source: 'ice-melt', target: 'sea-level', type: 'positive' },
      { id: 'c18', source: 'ice-melt', target: 'temperature', type: 'positive' },
      { id: 'c19', source: 'sea-level', target: 'economic-damage', type: 'positive' },
    ],
    loops: [
      { id: 'B1', name: 'Policy Response', type: 'balancing', nodes: ['emissions', 'temperature', 'extreme-weather', 'public-concern', 'political-will', 'climate-policy'], description: 'Impacts drive concern, concern drives policy, policy reduces emissions' },
      { id: 'R1', name: 'Fossil Resistance', type: 'reinforcing', nodes: ['fossil-economy', 'resistance', 'climate-policy'], description: 'Fossil interests resist policy that threatens their economy' },
      { id: 'R2', name: 'Clean Tech Transition', type: 'reinforcing', nodes: ['climate-policy', 'clean-tech', 'fossil-economy'], description: 'Policy accelerates clean tech, displacing fossil economy' },
      { id: 'R3', name: 'Ice-Albedo Feedback', type: 'reinforcing', nodes: ['temperature', 'ice-melt'], description: 'Warming melts ice, reducing reflectivity, accelerating warming' },
    ],
  },

  'wealth-inequality': {
    id: 'wealth-inequality',
    name: 'Wealth Inequality Dynamics',
    domain: 'global',
    difficulty: 'advanced',
    type: 'cld',
    description: 'How wealth concentrates over time and the social dynamics it creates.',
    situation: 'Those with wealth can invest it to earn more, while those without struggle to save. This creates diverging trajectories that compound over generations.',
    keyLessons: [
      'Wealth compounds through investment returns',
      'Economic mobility becomes harder as gaps widen',
      'Education is key but access is often tied to wealth',
      'Political influence can entrench advantages',
      'Social cohesion suffers as inequality grows',
    ],
    elements: [
      { id: 'wealth-top', type: 'variable', label: 'Wealth (Top 10%)', x: 100, y: 100 },
      { id: 'investment-returns', type: 'variable', label: 'Investment Returns', x: 100, y: 220 },
      { id: 'political-influence', type: 'variable', label: 'Political Influence', x: 100, y: 340 },
      { id: 'favorable-policy', type: 'variable', label: 'Wealth-Favorable Policy', x: 100, y: 460 },
      { id: 'wealth-bottom', type: 'variable', label: 'Wealth (Bottom 50%)', x: 500, y: 100 },
      { id: 'wage-income', type: 'variable', label: 'Wage Income', x: 500, y: 220 },
      { id: 'cost-of-living', type: 'variable', label: 'Cost of Living', x: 500, y: 340 },
      { id: 'savings-rate', type: 'variable', label: 'Savings Rate', x: 500, y: 460 },
      { id: 'inequality-gap', type: 'variable', label: 'Inequality Gap', x: 300, y: 160 },
      { id: 'education-access', type: 'variable', label: 'Education Access', x: 300, y: 280 },
      { id: 'social-mobility', type: 'variable', label: 'Social Mobility', x: 300, y: 400 },
      { id: 'social-cohesion', type: 'variable', label: 'Social Cohesion', x: 300, y: 520 },
    ],
    connections: [
      { id: 'c1', source: 'wealth-top', target: 'investment-returns', type: 'positive' },
      { id: 'c2', source: 'investment-returns', target: 'wealth-top', type: 'positive' },
      { id: 'c3', source: 'wealth-top', target: 'political-influence', type: 'positive' },
      { id: 'c4', source: 'political-influence', target: 'favorable-policy', type: 'positive' },
      { id: 'c5', source: 'favorable-policy', target: 'wealth-top', type: 'positive' },
      { id: 'c6', source: 'wealth-bottom', target: 'wage-income', type: 'positive' },
      { id: 'c7', source: 'wage-income', target: 'savings-rate', type: 'positive' },
      { id: 'c8', source: 'cost-of-living', target: 'savings-rate', type: 'negative' },
      { id: 'c9', source: 'savings-rate', target: 'wealth-bottom', type: 'positive' },
      { id: 'c10', source: 'wealth-top', target: 'inequality-gap', type: 'positive' },
      { id: 'c11', source: 'wealth-bottom', target: 'inequality-gap', type: 'negative' },
      { id: 'c12', source: 'inequality-gap', target: 'education-access', type: 'negative' },
      { id: 'c13', source: 'education-access', target: 'social-mobility', type: 'positive' },
      { id: 'c14', source: 'social-mobility', target: 'wealth-bottom', type: 'positive' },
      { id: 'c15', source: 'inequality-gap', target: 'social-cohesion', type: 'negative' },
      { id: 'c16', source: 'favorable-policy', target: 'wage-income', type: 'negative' },
      { id: 'c17', source: 'wealth-top', target: 'cost-of-living', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Wealth Compounds', type: 'reinforcing', nodes: ['wealth-top', 'investment-returns'], description: 'More wealth enables more investment, generating more wealth' },
      { id: 'R2', name: 'Political Capture', type: 'reinforcing', nodes: ['wealth-top', 'political-influence', 'favorable-policy'], description: 'Wealth buys influence, influence shapes policy to increase wealth' },
      { id: 'B1', name: 'Mobility Path', type: 'balancing', nodes: ['inequality-gap', 'education-access', 'social-mobility', 'wealth-bottom'], description: 'Education provides path out of poverty, reducing gap' },
      { id: 'R3', name: 'Mobility Trap', type: 'reinforcing', nodes: ['inequality-gap', 'education-access', 'social-mobility', 'wealth-bottom'], description: 'As gap widens, education access falls, trapping people' },
    ],
  },

  'misinformation-spread': {
    id: 'misinformation-spread',
    name: 'Misinformation & Truth Decay',
    domain: 'global',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How false information spreads and why it\'s so hard to correct.',
    situation: 'Misinformation spreads faster than corrections. Emotional content gets shared more, and once beliefs form, they\'re resistant to facts that contradict them.',
    keyLessons: [
      'Emotional content spreads faster than factual content',
      'Confirmation bias makes corrections ineffective',
      'Trust in institutions affects susceptibility',
      'Social proof amplifies both truth and lies',
      'Echo chambers reinforce beliefs',
    ],
    elements: [
      { id: 'misinformation', type: 'variable', label: 'Misinformation Volume', x: 300, y: 100 },
      { id: 'emotional-content', type: 'variable', label: 'Emotional Intensity', x: 100, y: 100 },
      { id: 'sharing', type: 'variable', label: 'Social Sharing', x: 100, y: 220 },
      { id: 'exposure', type: 'variable', label: 'Exposure to Misinfo', x: 300, y: 220 },
      { id: 'belief', type: 'variable', label: 'False Beliefs', x: 500, y: 220 },
      { id: 'confirmation-bias', type: 'variable', label: 'Confirmation Bias', x: 500, y: 340 },
      { id: 'trust-media', type: 'variable', label: 'Trust in Media', x: 300, y: 340 },
      { id: 'trust-experts', type: 'variable', label: 'Trust in Experts', x: 100, y: 340 },
      { id: 'correction-effectiveness', type: 'variable', label: 'Correction Effectiveness', x: 300, y: 460 },
      { id: 'echo-chambers', type: 'variable', label: 'Echo Chambers', x: 500, y: 100 },
      { id: 'polarization', type: 'variable', label: 'Political Polarization', x: 500, y: 460 },
    ],
    connections: [
      { id: 'c1', source: 'misinformation', target: 'emotional-content', type: 'positive' },
      { id: 'c2', source: 'emotional-content', target: 'sharing', type: 'positive' },
      { id: 'c3', source: 'sharing', target: 'exposure', type: 'positive' },
      { id: 'c4', source: 'exposure', target: 'belief', type: 'positive' },
      { id: 'c5', source: 'belief', target: 'confirmation-bias', type: 'positive' },
      { id: 'c6', source: 'confirmation-bias', target: 'sharing', type: 'positive' },
      { id: 'c7', source: 'confirmation-bias', target: 'correction-effectiveness', type: 'negative' },
      { id: 'c8', source: 'trust-media', target: 'correction-effectiveness', type: 'positive' },
      { id: 'c9', source: 'trust-experts', target: 'correction-effectiveness', type: 'positive' },
      { id: 'c10', source: 'misinformation', target: 'trust-media', type: 'negative' },
      { id: 'c11', source: 'misinformation', target: 'trust-experts', type: 'negative' },
      { id: 'c12', source: 'echo-chambers', target: 'exposure', type: 'positive' },
      { id: 'c13', source: 'belief', target: 'echo-chambers', type: 'positive' },
      { id: 'c14', source: 'echo-chambers', target: 'polarization', type: 'positive' },
      { id: 'c15', source: 'polarization', target: 'trust-media', type: 'negative' },
      { id: 'c16', source: 'correction-effectiveness', target: 'belief', type: 'negative' },
    ],
    loops: [
      { id: 'R1', name: 'Viral Spread', type: 'reinforcing', nodes: ['emotional-content', 'sharing', 'exposure'], description: 'Emotional content gets shared, spreading further' },
      { id: 'R2', name: 'Confirmation Loop', type: 'reinforcing', nodes: ['belief', 'confirmation-bias', 'sharing', 'exposure'], description: 'Beliefs drive selective sharing, reinforcing beliefs' },
      { id: 'R3', name: 'Echo Chamber', type: 'reinforcing', nodes: ['belief', 'echo-chambers', 'exposure'], description: 'Beliefs create filter bubbles that reinforce those beliefs' },
      { id: 'R4', name: 'Trust Erosion', type: 'reinforcing', nodes: ['misinformation', 'trust-media', 'correction-effectiveness', 'belief'], description: 'Misinfo erodes trust, making corrections less effective' },
    ],
  },

  // === SOCIETY & COMMUNITY ===
  'education-system': {
    id: 'education-system',
    name: 'Education Quality Spiral',
    domain: 'society',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How education quality affects communities across generations.',
    situation: 'Quality education creates better outcomes, attracting resources and good teachers. Poor education leads to decline. This creates diverging trajectories between communities.',
    keyLessons: [
      'Education effects compound across generations',
      'Teacher quality is the biggest in-school factor',
      'Resources follow success, starving struggling schools',
      'Parent engagement and community support matter',
      'Early intervention has the highest return',
    ],
    elements: [
      { id: 'school-quality', type: 'variable', label: 'School Quality', x: 300, y: 150 },
      { id: 'student-outcomes', type: 'variable', label: 'Student Outcomes', x: 500, y: 150 },
      { id: 'teacher-quality', type: 'variable', label: 'Teacher Quality', x: 100, y: 150 },
      { id: 'teacher-pay', type: 'variable', label: 'Teacher Pay', x: 100, y: 280 },
      { id: 'funding', type: 'variable', label: 'School Funding', x: 300, y: 280 },
      { id: 'property-values', type: 'variable', label: 'Property Values', x: 500, y: 280 },
      { id: 'parent-engagement', type: 'variable', label: 'Parent Engagement', x: 100, y: 410 },
      { id: 'community-income', type: 'variable', label: 'Community Income', x: 300, y: 410 },
      { id: 'college-attendance', type: 'variable', label: 'College Attendance', x: 500, y: 410 },
      { id: 'future-earnings', type: 'variable', label: 'Future Earnings', x: 400, y: 530 },
      { id: 'next-gen-outcomes', type: 'variable', label: 'Next Generation Outcomes', x: 200, y: 530 },
    ],
    connections: [
      { id: 'c1', source: 'school-quality', target: 'student-outcomes', type: 'positive' },
      { id: 'c2', source: 'teacher-quality', target: 'school-quality', type: 'positive' },
      { id: 'c3', source: 'teacher-pay', target: 'teacher-quality', type: 'positive' },
      { id: 'c4', source: 'funding', target: 'teacher-pay', type: 'positive' },
      { id: 'c5', source: 'funding', target: 'school-quality', type: 'positive' },
      { id: 'c6', source: 'student-outcomes', target: 'property-values', type: 'positive' },
      { id: 'c7', source: 'property-values', target: 'funding', type: 'positive' },
      { id: 'c8', source: 'student-outcomes', target: 'college-attendance', type: 'positive' },
      { id: 'c9', source: 'college-attendance', target: 'future-earnings', type: 'positive' },
      { id: 'c10', source: 'future-earnings', target: 'community-income', type: 'positive' },
      { id: 'c11', source: 'community-income', target: 'parent-engagement', type: 'positive' },
      { id: 'c12', source: 'parent-engagement', target: 'student-outcomes', type: 'positive' },
      { id: 'c13', source: 'future-earnings', target: 'next-gen-outcomes', type: 'positive' },
      { id: 'c14', source: 'next-gen-outcomes', target: 'school-quality', type: 'positive' },
      { id: 'c15', source: 'community-income', target: 'funding', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Property Tax Loop', type: 'reinforcing', nodes: ['school-quality', 'student-outcomes', 'property-values', 'funding'], description: 'Good schools raise property values, which funds better schools' },
      { id: 'R2', name: 'Teacher Attraction', type: 'reinforcing', nodes: ['funding', 'teacher-pay', 'teacher-quality', 'school-quality'], description: 'Better funding attracts better teachers' },
      { id: 'R3', name: 'Generational Cycle', type: 'reinforcing', nodes: ['student-outcomes', 'college-attendance', 'future-earnings', 'next-gen-outcomes', 'school-quality'], description: 'Education compounds across generations' },
      { id: 'R4', name: 'Community Wealth', type: 'reinforcing', nodes: ['student-outcomes', 'future-earnings', 'community-income', 'parent-engagement'], description: 'Success builds community capacity to support schools' },
    ],
  },

  'healthcare-access': {
    id: 'healthcare-access',
    name: 'Healthcare Access & Outcomes',
    domain: 'society',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How healthcare access creates diverging health outcomes between communities.',
    situation: 'Access to preventive care reduces costs long-term but requires upfront investment. Without access, conditions worsen, costs rise, and health gaps widen.',
    keyLessons: [
      'Prevention is cheaper than treatment',
      'Health affects productivity and income',
      'Healthcare deserts compound disadvantage',
      'Emergency care is the most expensive care',
      'Health literacy affects utilization',
    ],
    elements: [
      { id: 'healthcare-access', type: 'variable', label: 'Healthcare Access', x: 300, y: 100 },
      { id: 'preventive-care', type: 'variable', label: 'Preventive Care', x: 100, y: 180 },
      { id: 'chronic-disease', type: 'variable', label: 'Chronic Disease', x: 500, y: 180 },
      { id: 'emergency-visits', type: 'variable', label: 'Emergency Visits', x: 500, y: 300 },
      { id: 'healthcare-costs', type: 'variable', label: 'Healthcare Costs', x: 300, y: 300 },
      { id: 'productivity', type: 'variable', label: 'Work Productivity', x: 100, y: 300 },
      { id: 'income', type: 'variable', label: 'Household Income', x: 100, y: 420 },
      { id: 'insurance', type: 'variable', label: 'Insurance Coverage', x: 300, y: 420 },
      { id: 'health-literacy', type: 'variable', label: 'Health Literacy', x: 500, y: 420 },
      { id: 'life-expectancy', type: 'variable', label: 'Life Expectancy', x: 300, y: 540 },
      { id: 'community-health', type: 'variable', label: 'Community Health', x: 100, y: 540 },
    ],
    connections: [
      { id: 'c1', source: 'healthcare-access', target: 'preventive-care', type: 'positive' },
      { id: 'c2', source: 'preventive-care', target: 'chronic-disease', type: 'negative' },
      { id: 'c3', source: 'chronic-disease', target: 'emergency-visits', type: 'positive' },
      { id: 'c4', source: 'emergency-visits', target: 'healthcare-costs', type: 'positive' },
      { id: 'c5', source: 'preventive-care', target: 'healthcare-costs', type: 'negative' },
      { id: 'c6', source: 'healthcare-costs', target: 'income', type: 'negative' },
      { id: 'c7', source: 'income', target: 'insurance', type: 'positive' },
      { id: 'c8', source: 'insurance', target: 'healthcare-access', type: 'positive' },
      { id: 'c9', source: 'chronic-disease', target: 'productivity', type: 'negative' },
      { id: 'c10', source: 'productivity', target: 'income', type: 'positive' },
      { id: 'c11', source: 'healthcare-access', target: 'health-literacy', type: 'positive' },
      { id: 'c12', source: 'health-literacy', target: 'preventive-care', type: 'positive' },
      { id: 'c13', source: 'preventive-care', target: 'life-expectancy', type: 'positive' },
      { id: 'c14', source: 'chronic-disease', target: 'life-expectancy', type: 'negative' },
      { id: 'c15', source: 'life-expectancy', target: 'community-health', type: 'positive' },
      { id: 'c16', source: 'community-health', target: 'productivity', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Prevention Dividend', type: 'reinforcing', nodes: ['healthcare-access', 'preventive-care', 'chronic-disease', 'healthcare-costs', 'income', 'insurance'], description: 'Access enables prevention, reducing costs, improving access' },
      { id: 'R2', name: 'Disease Spiral', type: 'reinforcing', nodes: ['chronic-disease', 'productivity', 'income', 'insurance', 'healthcare-access', 'preventive-care'], description: 'Disease reduces income, reducing access, worsening disease' },
      { id: 'R3', name: 'Health Literacy', type: 'reinforcing', nodes: ['healthcare-access', 'health-literacy', 'preventive-care'], description: 'Access builds health knowledge, improving utilization' },
      { id: 'B1', name: 'Emergency Cost Pressure', type: 'balancing', nodes: ['chronic-disease', 'emergency-visits', 'healthcare-costs'], description: 'Unmanaged conditions drive expensive emergency care' },
    ],
  },

  'urban-housing': {
    id: 'urban-housing',
    name: 'Urban Housing Crisis',
    domain: 'society',
    difficulty: 'advanced',
    type: 'cld',
    description: 'Why cities struggle to provide affordable housing as they grow.',
    situation: 'Growing cities attract jobs, which attracts people, which raises housing demand. But supply can\'t keep up, prices rise, and essential workers get pushed out.',
    keyLessons: [
      'Housing supply is slow to respond to demand',
      'Success attracts more success (and more demand)',
      'Existing homeowners resist new construction',
      'Workers essential to the city get priced out',
      'Transportation and housing are linked',
    ],
    elements: [
      { id: 'jobs', type: 'variable', label: 'Job Opportunities', x: 100, y: 100 },
      { id: 'population', type: 'variable', label: 'Population', x: 300, y: 100 },
      { id: 'housing-demand', type: 'variable', label: 'Housing Demand', x: 500, y: 100 },
      { id: 'home-prices', type: 'variable', label: 'Home Prices', x: 500, y: 230 },
      { id: 'housing-supply', type: 'variable', label: 'Housing Supply', x: 300, y: 230 },
      { id: 'construction', type: 'variable', label: 'New Construction', x: 100, y: 230 },
      { id: 'homeowner-opposition', type: 'variable', label: 'NIMBY Opposition', x: 100, y: 360 },
      { id: 'displacement', type: 'variable', label: 'Worker Displacement', x: 500, y: 360 },
      { id: 'commute-distance', type: 'variable', label: 'Commute Distance', x: 500, y: 480 },
      { id: 'traffic', type: 'variable', label: 'Traffic Congestion', x: 300, y: 480 },
      { id: 'quality-of-life', type: 'variable', label: 'Quality of Life', x: 100, y: 480 },
      { id: 'city-attractiveness', type: 'variable', label: 'City Attractiveness', x: 200, y: 580 },
    ],
    connections: [
      { id: 'c1', source: 'jobs', target: 'population', type: 'positive' },
      { id: 'c2', source: 'population', target: 'housing-demand', type: 'positive' },
      { id: 'c3', source: 'housing-demand', target: 'home-prices', type: 'positive' },
      { id: 'c4', source: 'housing-supply', target: 'home-prices', type: 'negative' },
      { id: 'c5', source: 'construction', target: 'housing-supply', type: 'positive' },
      { id: 'c6', source: 'home-prices', target: 'construction', type: 'positive' },
      { id: 'c7', source: 'homeowner-opposition', target: 'construction', type: 'negative' },
      { id: 'c8', source: 'home-prices', target: 'homeowner-opposition', type: 'positive' },
      { id: 'c9', source: 'home-prices', target: 'displacement', type: 'positive' },
      { id: 'c10', source: 'displacement', target: 'commute-distance', type: 'positive' },
      { id: 'c11', source: 'commute-distance', target: 'traffic', type: 'positive' },
      { id: 'c12', source: 'traffic', target: 'quality-of-life', type: 'negative' },
      { id: 'c13', source: 'quality-of-life', target: 'city-attractiveness', type: 'positive' },
      { id: 'c14', source: 'city-attractiveness', target: 'jobs', type: 'positive' },
      { id: 'c15', source: 'displacement', target: 'jobs', type: 'negative', curve: 60 },
      { id: 'c16', source: 'population', target: 'jobs', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Urban Growth', type: 'reinforcing', nodes: ['jobs', 'population', 'housing-demand'], description: 'Jobs attract people, people attract more jobs' },
      { id: 'B1', name: 'Market Response', type: 'balancing', nodes: ['home-prices', 'construction', 'housing-supply'], description: 'High prices incentivize construction' },
      { id: 'R2', name: 'NIMBY Block', type: 'reinforcing', nodes: ['home-prices', 'homeowner-opposition', 'construction', 'housing-supply'], description: 'High prices create opposition to new supply' },
      { id: 'R3', name: 'Displacement Spiral', type: 'reinforcing', nodes: ['home-prices', 'displacement', 'commute-distance', 'traffic', 'quality-of-life', 'city-attractiveness', 'jobs', 'population', 'housing-demand'], description: 'Displacement degrades quality of life' },
    ],
  },

  'social-movements': {
    id: 'social-movements',
    name: 'Social Movement Dynamics',
    domain: 'society',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How social movements grow, succeed, or fade away.',
    situation: 'A social movement starts small but can grow through visibility, success, and network effects. But movements also face backlash and can burn out.',
    keyLessons: [
      'Visibility attracts supporters and opposition',
      'Early wins build momentum',
      'Sustained effort requires organization',
      'Backlash is part of progress',
      'Movements need both passion and strategy',
    ],
    elements: [
      { id: 'grievance', type: 'variable', label: 'Public Grievance', x: 100, y: 100 },
      { id: 'activism', type: 'variable', label: 'Activist Activity', x: 300, y: 100 },
      { id: 'visibility', type: 'variable', label: 'Media Visibility', x: 500, y: 100 },
      { id: 'public-support', type: 'variable', label: 'Public Support', x: 500, y: 230 },
      { id: 'new-activists', type: 'variable', label: 'New Activists', x: 300, y: 230 },
      { id: 'political-pressure', type: 'variable', label: 'Political Pressure', x: 100, y: 230 },
      { id: 'policy-wins', type: 'variable', label: 'Policy Wins', x: 100, y: 360 },
      { id: 'momentum', type: 'variable', label: 'Movement Momentum', x: 300, y: 360 },
      { id: 'backlash', type: 'variable', label: 'Opposition Backlash', x: 500, y: 360 },
      { id: 'burnout', type: 'variable', label: 'Activist Burnout', x: 300, y: 480 },
      { id: 'organization', type: 'variable', label: 'Organization Capacity', x: 100, y: 480 },
    ],
    connections: [
      { id: 'c1', source: 'grievance', target: 'activism', type: 'positive' },
      { id: 'c2', source: 'activism', target: 'visibility', type: 'positive' },
      { id: 'c3', source: 'visibility', target: 'public-support', type: 'positive' },
      { id: 'c4', source: 'public-support', target: 'new-activists', type: 'positive' },
      { id: 'c5', source: 'new-activists', target: 'activism', type: 'positive' },
      { id: 'c6', source: 'public-support', target: 'political-pressure', type: 'positive' },
      { id: 'c7', source: 'political-pressure', target: 'policy-wins', type: 'positive' },
      { id: 'c8', source: 'policy-wins', target: 'momentum', type: 'positive' },
      { id: 'c9', source: 'momentum', target: 'activism', type: 'positive' },
      { id: 'c10', source: 'visibility', target: 'backlash', type: 'positive' },
      { id: 'c11', source: 'backlash', target: 'political-pressure', type: 'negative' },
      { id: 'c12', source: 'activism', target: 'burnout', type: 'positive' },
      { id: 'c13', source: 'burnout', target: 'activism', type: 'negative' },
      { id: 'c14', source: 'organization', target: 'burnout', type: 'negative' },
      { id: 'c15', source: 'policy-wins', target: 'grievance', type: 'negative' },
      { id: 'c16', source: 'new-activists', target: 'organization', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Visibility Growth', type: 'reinforcing', nodes: ['activism', 'visibility', 'public-support', 'new-activists'], description: 'Activism creates visibility, attracting supporters' },
      { id: 'R2', name: 'Victory Momentum', type: 'reinforcing', nodes: ['activism', 'political-pressure', 'policy-wins', 'momentum'], description: 'Wins energize the movement' },
      { id: 'B1', name: 'Goal Achievement', type: 'balancing', nodes: ['policy-wins', 'grievance', 'activism'], description: 'Success reduces the grievance that started it' },
      { id: 'B2', name: 'Burnout Drain', type: 'balancing', nodes: ['activism', 'burnout'], description: 'Sustained activism leads to exhaustion' },
      { id: 'B3', name: 'Backlash Resistance', type: 'balancing', nodes: ['visibility', 'backlash', 'political-pressure', 'policy-wins'], description: 'Success triggers opposition' },
    ],
  },

  // === TECHNOLOGY & AI ===
  'ai-adoption': {
    id: 'ai-adoption',
    name: 'AI Adoption & Disruption',
    domain: 'technology',
    difficulty: 'advanced',
    type: 'cld',
    description: 'How AI transforms industries through adoption dynamics and feedback loops.',
    situation: 'AI capabilities improve, leading to adoption, which generates data and investment for further improvement. But this creates winners and losers, changing the competitive landscape.',
    keyLessons: [
      'Data creates competitive moats',
      'Early adopters gain compounding advantages',
      'AI amplifies existing inequalities',
      'Talent concentration accelerates leaders',
      'Regulation lags behind technology',
    ],
    elements: [
      { id: 'ai-capability', type: 'variable', label: 'AI Capability', x: 300, y: 100 },
      { id: 'adoption', type: 'variable', label: 'AI Adoption', x: 500, y: 100 },
      { id: 'data-generated', type: 'variable', label: 'Data Generated', x: 500, y: 230 },
      { id: 'training-data', type: 'variable', label: 'Training Data Quality', x: 300, y: 230 },
      { id: 'investment', type: 'variable', label: 'AI Investment', x: 100, y: 230 },
      { id: 'productivity-gains', type: 'variable', label: 'Productivity Gains', x: 500, y: 360 },
      { id: 'competitive-advantage', type: 'variable', label: 'Competitive Advantage', x: 300, y: 360 },
      { id: 'market-concentration', type: 'variable', label: 'Market Concentration', x: 100, y: 360 },
      { id: 'job-displacement', type: 'variable', label: 'Job Displacement', x: 500, y: 490 },
      { id: 'talent-concentration', type: 'variable', label: 'AI Talent Concentration', x: 100, y: 100 },
      { id: 'regulatory-pressure', type: 'variable', label: 'Regulatory Pressure', x: 300, y: 490 },
      { id: 'public-trust', type: 'variable', label: 'Public Trust in AI', x: 100, y: 490 },
    ],
    connections: [
      { id: 'c1', source: 'ai-capability', target: 'adoption', type: 'positive' },
      { id: 'c2', source: 'adoption', target: 'data-generated', type: 'positive' },
      { id: 'c3', source: 'data-generated', target: 'training-data', type: 'positive' },
      { id: 'c4', source: 'training-data', target: 'ai-capability', type: 'positive' },
      { id: 'c5', source: 'adoption', target: 'investment', type: 'positive' },
      { id: 'c6', source: 'investment', target: 'ai-capability', type: 'positive' },
      { id: 'c7', source: 'adoption', target: 'productivity-gains', type: 'positive' },
      { id: 'c8', source: 'productivity-gains', target: 'competitive-advantage', type: 'positive' },
      { id: 'c9', source: 'competitive-advantage', target: 'market-concentration', type: 'positive' },
      { id: 'c10', source: 'market-concentration', target: 'investment', type: 'positive' },
      { id: 'c11', source: 'talent-concentration', target: 'ai-capability', type: 'positive' },
      { id: 'c12', source: 'investment', target: 'talent-concentration', type: 'positive' },
      { id: 'c13', source: 'adoption', target: 'job-displacement', type: 'positive' },
      { id: 'c14', source: 'job-displacement', target: 'regulatory-pressure', type: 'positive' },
      { id: 'c15', source: 'regulatory-pressure', target: 'adoption', type: 'negative' },
      { id: 'c16', source: 'job-displacement', target: 'public-trust', type: 'negative' },
      { id: 'c17', source: 'public-trust', target: 'adoption', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Data Flywheel', type: 'reinforcing', nodes: ['adoption', 'data-generated', 'training-data', 'ai-capability'], description: 'Usage generates data that improves AI' },
      { id: 'R2', name: 'Investment Cycle', type: 'reinforcing', nodes: ['adoption', 'investment', 'ai-capability'], description: 'Success attracts investment in capabilities' },
      { id: 'R3', name: 'Winner Take All', type: 'reinforcing', nodes: ['productivity-gains', 'competitive-advantage', 'market-concentration', 'investment', 'ai-capability', 'adoption'], description: 'Leaders pull further ahead' },
      { id: 'R4', name: 'Talent Magnet', type: 'reinforcing', nodes: ['investment', 'talent-concentration', 'ai-capability'], description: 'Leaders attract the best AI talent' },
      { id: 'B1', name: 'Regulatory Brake', type: 'balancing', nodes: ['adoption', 'job-displacement', 'regulatory-pressure'], description: 'Disruption triggers regulation' },
    ],
  },

  'platform-dynamics': {
    id: 'platform-dynamics',
    name: 'Platform Network Effects',
    domain: 'technology',
    difficulty: 'intermediate',
    type: 'cld',
    description: 'How digital platforms grow through network effects and winner-take-all dynamics.',
    situation: 'A platform becomes more valuable as more users join. This creates powerful growth loops but also raises concerns about monopoly power and lock-in.',
    keyLessons: [
      'Network effects create exponential growth',
      'Switching costs lock users in',
      'Platforms capture value from ecosystems',
      'Winner-take-all markets have few survivors',
      'Data moats compound over time',
    ],
    elements: [
      { id: 'users', type: 'variable', label: 'User Base', x: 300, y: 100 },
      { id: 'value-to-users', type: 'variable', label: 'Value to Users', x: 500, y: 100 },
      { id: 'content-creators', type: 'variable', label: 'Content/Sellers', x: 100, y: 100 },
      { id: 'content-quality', type: 'variable', label: 'Content Quality', x: 100, y: 230 },
      { id: 'engagement', type: 'variable', label: 'User Engagement', x: 300, y: 230 },
      { id: 'data-collected', type: 'variable', label: 'Data Collected', x: 500, y: 230 },
      { id: 'ad-targeting', type: 'variable', label: 'Ad Targeting', x: 500, y: 360 },
      { id: 'revenue', type: 'variable', label: 'Platform Revenue', x: 300, y: 360 },
      { id: 'product-investment', type: 'variable', label: 'Product Investment', x: 100, y: 360 },
      { id: 'switching-cost', type: 'variable', label: 'Switching Costs', x: 100, y: 490 },
      { id: 'competitors', type: 'variable', label: 'Competitor Viability', x: 300, y: 490 },
      { id: 'market-power', type: 'variable', label: 'Market Power', x: 500, y: 490 },
    ],
    connections: [
      { id: 'c1', source: 'users', target: 'value-to-users', type: 'positive' },
      { id: 'c2', source: 'value-to-users', target: 'users', type: 'positive' },
      { id: 'c3', source: 'users', target: 'content-creators', type: 'positive' },
      { id: 'c4', source: 'content-creators', target: 'content-quality', type: 'positive' },
      { id: 'c5', source: 'content-quality', target: 'value-to-users', type: 'positive' },
      { id: 'c6', source: 'users', target: 'engagement', type: 'positive' },
      { id: 'c7', source: 'engagement', target: 'data-collected', type: 'positive' },
      { id: 'c8', source: 'data-collected', target: 'ad-targeting', type: 'positive' },
      { id: 'c9', source: 'ad-targeting', target: 'revenue', type: 'positive' },
      { id: 'c10', source: 'revenue', target: 'product-investment', type: 'positive' },
      { id: 'c11', source: 'product-investment', target: 'value-to-users', type: 'positive' },
      { id: 'c12', source: 'engagement', target: 'switching-cost', type: 'positive' },
      { id: 'c13', source: 'switching-cost', target: 'users', type: 'positive' },
      { id: 'c14', source: 'users', target: 'competitors', type: 'negative' },
      { id: 'c15', source: 'competitors', target: 'market-power', type: 'negative' },
      { id: 'c16', source: 'market-power', target: 'revenue', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Network Effect', type: 'reinforcing', nodes: ['users', 'value-to-users'], description: 'More users make platform more valuable' },
      { id: 'R2', name: 'Two-Sided Market', type: 'reinforcing', nodes: ['users', 'content-creators', 'content-quality', 'value-to-users'], description: 'Users attract creators, creators attract users' },
      { id: 'R3', name: 'Data Moat', type: 'reinforcing', nodes: ['users', 'engagement', 'data-collected', 'ad-targeting', 'revenue', 'product-investment', 'value-to-users'], description: 'Data enables better products and monetization' },
      { id: 'R4', name: 'Lock-In', type: 'reinforcing', nodes: ['engagement', 'switching-cost', 'users'], description: 'Heavy use creates lock-in' },
      { id: 'R5', name: 'Winner Take All', type: 'reinforcing', nodes: ['users', 'competitors', 'market-power', 'revenue', 'product-investment', 'value-to-users'], description: 'Success kills competition' },
    ],
  },

  'automation-jobs': {
    id: 'automation-jobs',
    name: 'Automation & Future of Work',
    domain: 'technology',
    difficulty: 'advanced',
    type: 'cld',
    description: 'How automation transforms employment, skills, and the economy.',
    situation: 'Automation increases productivity but displaces workers. New jobs emerge, but require different skills. The transition creates winners, losers, and social challenges.',
    keyLessons: [
      'Automation affects different jobs differently',
      'New jobs require new skills',
      'Transition periods create hardship',
      'Education systems lag behind needs',
      'Social safety nets matter during transitions',
    ],
    elements: [
      { id: 'automation', type: 'variable', label: 'Automation Level', x: 300, y: 100 },
      { id: 'productivity', type: 'variable', label: 'Productivity', x: 500, y: 100 },
      { id: 'routine-jobs', type: 'variable', label: 'Routine Jobs', x: 100, y: 100 },
      { id: 'unemployment', type: 'variable', label: 'Unemployment', x: 100, y: 230 },
      { id: 'wage-pressure', type: 'variable', label: 'Wage Pressure', x: 100, y: 360 },
      { id: 'economic-output', type: 'variable', label: 'Economic Output', x: 500, y: 230 },
      { id: 'new-job-creation', type: 'variable', label: 'New Job Creation', x: 500, y: 360 },
      { id: 'skills-gap', type: 'variable', label: 'Skills Gap', x: 300, y: 230 },
      { id: 'training-investment', type: 'variable', label: 'Training Investment', x: 300, y: 360 },
      { id: 'inequality', type: 'variable', label: 'Income Inequality', x: 100, y: 490 },
      { id: 'consumer-demand', type: 'variable', label: 'Consumer Demand', x: 300, y: 490 },
      { id: 'automation-investment', type: 'variable', label: 'Automation Investment', x: 500, y: 490 },
    ],
    connections: [
      { id: 'c1', source: 'automation', target: 'productivity', type: 'positive' },
      { id: 'c2', source: 'automation', target: 'routine-jobs', type: 'negative' },
      { id: 'c3', source: 'routine-jobs', target: 'unemployment', type: 'negative' },
      { id: 'c4', source: 'unemployment', target: 'wage-pressure', type: 'positive' },
      { id: 'c5', source: 'productivity', target: 'economic-output', type: 'positive' },
      { id: 'c6', source: 'economic-output', target: 'new-job-creation', type: 'positive' },
      { id: 'c7', source: 'new-job-creation', target: 'unemployment', type: 'negative' },
      { id: 'c8', source: 'automation', target: 'skills-gap', type: 'positive' },
      { id: 'c9', source: 'skills-gap', target: 'unemployment', type: 'positive' },
      { id: 'c10', source: 'skills-gap', target: 'training-investment', type: 'positive' },
      { id: 'c11', source: 'training-investment', target: 'skills-gap', type: 'negative' },
      { id: 'c12', source: 'wage-pressure', target: 'inequality', type: 'positive' },
      { id: 'c13', source: 'inequality', target: 'consumer-demand', type: 'negative' },
      { id: 'c14', source: 'consumer-demand', target: 'economic-output', type: 'positive' },
      { id: 'c15', source: 'wage-pressure', target: 'automation-investment', type: 'positive' },
      { id: 'c16', source: 'automation-investment', target: 'automation', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Productivity Growth', type: 'reinforcing', nodes: ['automation', 'productivity', 'economic-output', 'new-job-creation'], description: 'Automation drives growth and new jobs' },
      { id: 'R2', name: 'Wage-Automation Spiral', type: 'reinforcing', nodes: ['automation', 'routine-jobs', 'unemployment', 'wage-pressure', 'automation-investment'], description: 'Displacement pressures wages, incentivizing more automation' },
      { id: 'B1', name: 'Skills Adaptation', type: 'balancing', nodes: ['skills-gap', 'training-investment'], description: 'Gaps trigger training investment' },
      { id: 'B2', name: 'Demand Constraint', type: 'balancing', nodes: ['wage-pressure', 'inequality', 'consumer-demand', 'economic-output', 'new-job-creation', 'unemployment'], description: 'Inequality reduces demand, limiting growth' },
    ],
  },

  'digital-addiction': {
    id: 'digital-addiction',
    name: 'Digital Addiction Loop',
    domain: 'technology',
    difficulty: 'beginner',
    type: 'cld',
    description: 'How apps are designed to be addictive and the impact on attention and wellbeing.',
    situation: 'Tech companies optimize for engagement using variable rewards, social validation, and personalization. This captures attention but fragments focus and affects mental health.',
    keyLessons: [
      'Variable rewards are highly addictive',
      'Attention is the currency of the digital economy',
      'Personalization increases engagement and addiction',
      'Fragmented attention affects deep work',
      'Design choices have societal consequences',
    ],
    elements: [
      { id: 'app-usage', type: 'variable', label: 'App Usage Time', x: 300, y: 100 },
      { id: 'notifications', type: 'variable', label: 'Notifications', x: 100, y: 100 },
      { id: 'variable-rewards', type: 'variable', label: 'Variable Rewards', x: 100, y: 230 },
      { id: 'dopamine', type: 'variable', label: 'Dopamine Response', x: 300, y: 230 },
      { id: 'craving', type: 'variable', label: 'Craving/Checking', x: 500, y: 230 },
      { id: 'personalization', type: 'variable', label: 'Content Personalization', x: 500, y: 100 },
      { id: 'attention-span', type: 'variable', label: 'Attention Span', x: 100, y: 360 },
      { id: 'deep-work', type: 'variable', label: 'Deep Work Capacity', x: 300, y: 360 },
      { id: 'productivity', type: 'variable', label: 'Productivity', x: 500, y: 360 },
      { id: 'boredom-tolerance', type: 'variable', label: 'Boredom Tolerance', x: 100, y: 490 },
      { id: 'real-activities', type: 'variable', label: 'Real-World Activities', x: 300, y: 490 },
      { id: 'wellbeing', type: 'variable', label: 'Overall Wellbeing', x: 500, y: 490 },
    ],
    connections: [
      { id: 'c1', source: 'notifications', target: 'app-usage', type: 'positive' },
      { id: 'c2', source: 'app-usage', target: 'variable-rewards', type: 'positive' },
      { id: 'c3', source: 'variable-rewards', target: 'dopamine', type: 'positive' },
      { id: 'c4', source: 'dopamine', target: 'craving', type: 'positive' },
      { id: 'c5', source: 'craving', target: 'app-usage', type: 'positive' },
      { id: 'c6', source: 'app-usage', target: 'personalization', type: 'positive' },
      { id: 'c7', source: 'personalization', target: 'variable-rewards', type: 'positive' },
      { id: 'c8', source: 'app-usage', target: 'attention-span', type: 'negative' },
      { id: 'c9', source: 'attention-span', target: 'deep-work', type: 'positive' },
      { id: 'c10', source: 'deep-work', target: 'productivity', type: 'positive' },
      { id: 'c11', source: 'app-usage', target: 'boredom-tolerance', type: 'negative' },
      { id: 'c12', source: 'boredom-tolerance', target: 'real-activities', type: 'positive' },
      { id: 'c13', source: 'boredom-tolerance', target: 'app-usage', type: 'negative' },
      { id: 'c14', source: 'real-activities', target: 'wellbeing', type: 'positive' },
      { id: 'c15', source: 'app-usage', target: 'real-activities', type: 'negative' },
      { id: 'c16', source: 'productivity', target: 'wellbeing', type: 'positive' },
    ],
    loops: [
      { id: 'R1', name: 'Dopamine Loop', type: 'reinforcing', nodes: ['app-usage', 'variable-rewards', 'dopamine', 'craving'], description: 'Rewards trigger cravings for more' },
      { id: 'R2', name: 'Personalization Trap', type: 'reinforcing', nodes: ['app-usage', 'personalization', 'variable-rewards', 'dopamine', 'craving'], description: 'Usage enables better targeting, increasing engagement' },
      { id: 'R3', name: 'Boredom Intolerance', type: 'reinforcing', nodes: ['app-usage', 'boredom-tolerance'], description: 'Digital stimulation reduces ability to tolerate boredom' },
      { id: 'B1', name: 'Attention Degradation', type: 'balancing', nodes: ['app-usage', 'attention-span', 'deep-work', 'productivity', 'wellbeing'], description: 'Heavy use degrades attention and productivity' },
    ],
  },
};

/**
 * Get all examples as an array
 */
export function getAllExamples() {
  return Object.values(EXAMPLES);
}

/**
 * Get examples by domain
 */
export function getExamplesByDomain(domain) {
  return Object.values(EXAMPLES).filter(ex => ex.domain === domain);
}

/**
 * Get examples by difficulty
 */
export function getExamplesByDifficulty(difficulty) {
  return Object.values(EXAMPLES).filter(ex => ex.difficulty === difficulty);
}

/**
 * Search examples by text
 */
export function searchExamples(query) {
  const q = query.toLowerCase();
  return Object.values(EXAMPLES).filter(ex =>
    ex.name.toLowerCase().includes(q) ||
    ex.description.toLowerCase().includes(q) ||
    ex.keyLessons.some(l => l.toLowerCase().includes(q))
  );
}

/**
 * Get a specific example by ID
 */
export function getExample(id) {
  return EXAMPLES[id] || null;
}
